-- Firestore: Collection Schema + Documents
-- Features: composite indexes, collection group indexes,
--           subcollections, deeply nested documents,
--           array fields, reference fields, timestamps
--
-- Firestore does not use SQL natively. These definitions show the
-- equivalent schema design for the LocalCloud Firestore emulator.
-- Use the Firestore admin API (gRPC)/seed.yaml to create these.

-- ============================================================
-- COLLECTION GROUPS & COMPOSITE INDEXES
-- ============================================================

-- Equivalent to creating these indexes via gcloud:

-- Composite: find users by role sorted by creation date
-- gcloud firestore indexes composite create \
--   --collection-group=users \
--   --field-config field-path=role,order=ASCENDING \
--   --field-config field-path=createdAt,order=DESCENDING \
--   --project=local-project

-- Composite: find users by organization name
-- gcloud firestore indexes composite create \
--   --collection-group=users \
--   --field-config field-path=organization.name,order=ASCENDING \
--   --field-config field-path=email,order=ASCENDING \
--   --project=local-project

-- Composite: find organizations by tier and member count
-- gcloud firestore indexes composite create \
--   --collection-group=organizations \
--   --field-config field-path=tier,order=ASCENDING \
--   --field-config field-path=memberCount,order=DESCENDING \
--   --project=local-project

-- Composite: find products by category and price
-- gcloud firestore indexes composite create \
--   --collection-group=products \
--   --field-config field-path=category,order=ASCENDING \
--   --field-config field-path=price,order=DESCENDING \
--   --project=local-project

-- Composite: find orders by status and creation date
-- gcloud firestore indexes composite create \
--   --collection-group=orders \
--   --field-config field-path=status,order=ASCENDING \
--   --field-config field-path=createdAt,order=DESCENDING \
--   --project=local-project

-- Composite: find events by type and timestamp (for audit trails)
-- gcloud firestore indexes composite create \
--   --collection-group=events \
--   --field-config field-path=type,order=ASCENDING \
--   --field-config field-path=timestamp,order=DESCENDING \
--   --project=local-project

-- COLLECTION GROUP indexes: query across all subcollections
-- gcloud firestore indexes composite create \
--   --collection-group=addresses \
--   --field-config field-path=type,order=ASCENDING \
--   --query-scope=COLLECTION_GROUP \
--   --project=local-project

-- gcloud firestore indexes composite create \
--   --collection-group=inventory \
--   --field-config field-path=quantity,order=ASCENDING \
--   --query-scope=COLLECTION_GROUP \
--   --project=local-project

-- gcloud firestore indexes composite create \
--   --collection-group=reviews \
--   --field-config field-path=rating,order=DESCENDING \
--   --query-scope=COLLECTION_GROUP \
--   --project=local-project

-- ============================================================
-- DOCUMENT SCHEMA (Represented as JSON for reference)
-- These are representative document structures, not SQL.
-- Use the Firestore REST/gRPC API or seed.yaml to create.
-- ============================================================

-- === USERS COLLECTION (10 documents) ===
-- /users/user-1
-- {
--   "name": "Alice Johnson",
--   "email": "alice@example.com",
--   "role": "admin",
--   "tier": "enterprise",
--   "status": "active",
--   "phone": "+1-415-555-0101",
--   "avatar": "https://storage.googleapis.com/profiles/alice.jpg",
--   "organization": {
--     "id": "org-1", "name": "Acme Corp", "title": "CTO", "department": "Engineering"
--   },
--   "preferences": {
--     "theme": "dark",
--     "notifications": { "email": true, "push": true, "sms": false, "digest": "weekly" },
--     "timezone": "America/Los_Angeles", "locale": "en-US",
--     "features": { "beta": true, "experimental_ai": true, "new_dashboard": false }
--   },
--   "security": {
--     "mfa_enabled": true, "mfa_method": "totp",
--     "last_password_change": Timestamp("2025-03-15T10:00:00Z"),
--     "login_provider": "google",
--     "sessions": [
--       { "device": "MacBook Pro", "ip": "192.168.1.100", "last_active": Timestamp("2025-05-20T14:22:00Z") }
--     ]
--   },
--   "addresses": [
--     { "type": "shipping", "label": "Home", "street": "100 Market St", "city": "San Francisco", "state": "CA", "country": "US", "is_default": true },
--     { "type": "billing", "label": "Corporate", "street": "600 California St", "city": "San Francisco", "state": "CA", "country": "US", "is_default": true }
--   ],
--   "tags": ["vip", "early-adopter", "reference-customer"],
--   "metrics": { "total_orders": 12, "total_spent": 15678.50, "avg_order_value": 1306.54, "lifetime_value_tier": "platinum" },
--   "createdAt": Timestamp("2024-01-15T08:30:00Z"),
--   "updatedAt": Timestamp("2025-05-20T14:22:00Z")
-- }

-- /users/user-2
-- {
--   "name": "Bob Smith",
--   "email": "bob@techcorp.com",
--   "role": "editor",
--   "tier": "pro",
--   "tags": ["developer"],
--   "organization": { "id": "org-2", "name": "TechCorp", "title": "Lead Engineer" },
--   "preferences": { "theme": "light", "timezone": "America/Los_Angeles", "locale": "en-US" },
--   "metrics": { "total_orders": 8, "total_spent": 4520.00, "avg_order_value": 565.00, "lifetime_value_tier": "gold" },
--   "createdAt": Timestamp("2024-02-20T10:00:00Z"),
--   "updatedAt": Timestamp("2025-05-19T09:15:00Z")
-- }

-- === ORGANIZATIONS COLLECTION (5 documents) ===
-- /organizations/org-1
-- {
--   "name": "Acme Corp",
--   "domain": "acme.com",
--   "tier": "enterprise",
--   "plan": "enterprise-annual",
--   "billing": {
--     "method": "invoice", "currency": "USD", "monthly_spend": 12500.00,
--     "payment_terms": "net-30",
--     "address": { "street": "600 California St", "city": "San Francisco", "state": "CA", "country": "US" }
--   },
--   "settings": {
--     "max_users": 100, "sso_enabled": true, "sso_provider": "okta",
--     "audit_logging": true, "data_retention_days": 365,
--     "ip_whitelist": ["203.0.113.0/24", "10.0.0.0/8"]
--   },
--   "memberCount": 45,
--   "createdAt": Timestamp("2023-06-01T08:00:00Z"),
--   "updatedAt": Timestamp("2025-05-20T10:00:00Z")
-- }

-- === PRODUCTS COLLECTION (15 documents) ===
-- /products/prod-1 (Cloud IDE Pro License)
-- { "name": "Cloud IDE Pro License", "sku": "CLD-IDE-001",
--   "category": "Software", "subcategory": "IDE", "brand": "LocalCloud",
--   "price": 29.99, "compareAtPrice": 49.99, "cost": 8.50,
--   "attributes": { "licenseType": "subscription", "features": ["ai-completion", "collaboration"] },
--   "tags": ["ide", "development", "cloud"], "rating": 4.5, "reviewCount": 234,
--   "inStock": true, "isDigital": true,
--   "createdAt": Timestamp("2024-01-01"), "updatedAt": Timestamp("2025-05-20")
-- }

-- === ORDERS COLLECTION (30+ documents) ===
-- Each order has an 'items' subcollection
-- /orders/ord-001
-- {
--   "orderId": "ord-001",
--   "customerId": "user-1",
--   "customerName": "Alice Johnson",
--   "status": "delivered",
--   "total": 229.98, "subtotal": 199.00, "tax": 19.90, "shipping": 9.99,
--   "currency": "USD", "paymentMethod": "visa", "gateway": "stripe",
--   "shippingAddress": { "street": "100 Market St", "city": "San Francisco", "state": "CA", "country": "US" },
--   "promoCodes": ["WELCOME10"],
--   "orderDate": Timestamp("2025-01-20T10:30:00Z"),
--   "paidAt": Timestamp("2025-01-20T10:35:00Z"),
--   "deliveredAt": Timestamp("2025-01-23T09:00:00Z")
-- }
-- Subcollection: /orders/ord-001/items
--   /orders/ord-001/items/item-1: { "productId": "prod-1", "productName": "Cloud IDE Pro License", "qty": 1, "price": 29.99 }
--   /orders/ord-001/items/item-2: { "productId": "prod-2", "productName": "Kubernetes Mastery Course", "qty": 1, "price": 199.00 }

-- === EVENTS COLLECTION (audit trail, analytics) ===
-- /events/evt-001
-- { "type": "order.created", "userId": "user-1",
--   "ip": "192.168.1.100",
--   "data": { "orderId": "ord-001", "total": 229.98 },
--   "timestamp": Timestamp("2025-01-20T10:30:00Z")
-- }
