-- PostgreSQL: Core Platform Tables
-- These are the shared infrastructure tables used by all emulators.
-- Run against the LocalCloud PostgreSQL database (port 5432).
--
-- Features: UPSERT, JSONB, indexes, composite PKs, GENERATED BY DEFAULT, SERIAL

-- ============================================================
-- TABLE DEFINITIONS
-- ============================================================

-- Projects: top-level GCP project registry
CREATE TABLE IF NOT EXISTS projects (
    project_id    VARCHAR(255) NOT NULL PRIMARY KEY,
    display_name  VARCHAR(255),
    labels        JSONB DEFAULT '{}',
    state         VARCHAR(20) DEFAULT 'ACTIVE',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Schema version tracking
CREATE TABLE IF NOT EXISTS schema_version (
    version     INT NOT NULL,
    applied_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Usage metrics: per-project, per-service request counters (UPSERT semantics)
CREATE TABLE IF NOT EXISTS usage_metrics (
    project_id    VARCHAR(255) NOT NULL,
    service_id    VARCHAR(255) NOT NULL,
    request_count BIGINT NOT NULL DEFAULT 0,
    last_updated  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (project_id, service_id)
);

-- Query history: SQL execution log from the browse/query console
CREATE TABLE IF NOT EXISTS query_history (
    id            BIGSERIAL PRIMARY KEY,
    project_id    VARCHAR(255) NOT NULL,
    service       VARCHAR(64) NOT NULL,
    sql           TEXT NOT NULL,
    instance      VARCHAR(255),
    database_name VARCHAR(255),
    duration_ms   BIGINT DEFAULT 0,
    row_count     INT DEFAULT 0,
    success       BOOLEAN DEFAULT TRUE,
    error_message TEXT,
    executed_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_query_history_project
    ON query_history (project_id, service, executed_at DESC);

-- Service routing: per-service local/remote mode
CREATE TABLE IF NOT EXISTS service_routing (
    project_id    VARCHAR(255) NOT NULL,
    service_id    VARCHAR(255) NOT NULL,
    mode          VARCHAR(20) DEFAULT 'local',
    remote_project VARCHAR(255),
    remote_region VARCHAR(255),
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (project_id, service_id)
);

-- Service config: UI enable/disable toggles
CREATE TABLE IF NOT EXISTS service_config (
    service_id  VARCHAR(255) PRIMARY KEY,
    enabled     BOOLEAN NOT NULL,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- GCS bucket project ownership tracking
CREATE TABLE IF NOT EXISTS gcs_bucket_projects (
    bucket_name VARCHAR(255) NOT NULL PRIMARY KEY,
    project_id  VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Telemetry queue: unsent events for retry
CREATE TABLE IF NOT EXISTS telemetry_queue (
    id          SERIAL PRIMARY KEY,
    event_json  TEXT NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- SAMPLE DATA
-- ============================================================

INSERT INTO projects (project_id, display_name, labels, state) VALUES
    ('local-project', 'Default Project', '{"env":"development","team":"platform","region":"us-central1"}', 'ACTIVE'),
    ('demo-project', 'Demo Project', '{"env":"demo","team":"sales"}', 'ACTIVE'),
    ('staging-project', 'Staging Project', '{"env":"staging","team":"engineering"}', 'ACTIVE'),
    ('prod-mirror', 'Production Mirror', '{"env":"production-mirror","team":"sre"}', 'ACTIVE')
ON CONFLICT (project_id) DO NOTHING;

INSERT INTO usage_metrics (project_id, service_id, request_count) VALUES
    ('local-project', 'gcs', 15234),
    ('local-project', 'pubsub', 8921),
    ('local-project', 'bigquery', 4567),
    ('local-project', 'spanner', 3210),
    ('local-project', 'secretmanager', 2345),
    ('local-project', 'cloudtasks', 1890),
    ('local-project', 'logging', 45678),
    ('local-project', 'monitoring', 12345),
    ('local-project', 'compute', 567),
    ('local-project', 'cloudrun', 890),
    ('local-project', 'gke', 234),
    ('local-project', 'memorystore', 7890),
    ('local-project', 'workflows', 3456),
    ('local-project', 'vertexai', 1234),
    ('local-project', 'kms', 5678),
    ('local-project', 'cloudsql', 2345),
    ('local-project', 'alloydb', 789),
    ('local-project', 'cloudscheduler', 345),
    ('local-project', 'cloudfunctions', 212),
    ('local-project', 'dataproc', 156),
    ('local-project', 'iam', 4567)
ON CONFLICT (project_id, service_id) DO NOTHING;

INSERT INTO service_config (service_id, enabled) VALUES
    ('gcs', TRUE), ('pubsub', TRUE), ('firestore', TRUE), ('bigquery', TRUE),
    ('spanner', TRUE), ('bigtable', TRUE), ('secretmanager', TRUE), ('cloudtasks', TRUE),
    ('logging', TRUE), ('monitoring', TRUE), ('memorystore', TRUE), ('workflows', TRUE),
    ('cloudscheduler', TRUE), ('cloudfunctions', TRUE), ('alloydb', TRUE), ('dataproc', TRUE),
    ('iam', TRUE), ('cloudsql', TRUE), ('kms', FALSE), ('vertexai', FALSE),
    ('compute', FALSE), ('cloudrun', FALSE), ('gke', FALSE)
ON CONFLICT (service_id) DO NOTHING;

INSERT INTO service_routing (project_id, service_id, mode) VALUES
    ('local-project', 'gcs', 'local'),
    ('local-project', 'pubsub', 'local'),
    ('local-project', 'spanner', 'local'),
    ('local-project', 'bigquery', 'local'),
    ('local-project', 'secretmanager', 'local')
ON CONFLICT (project_id, service_id) DO NOTHING;

INSERT INTO query_history (project_id, service, sql, instance, database_name, duration_ms, row_count, success, executed_at) VALUES
    ('local-project', 'bigquery', 'SELECT COUNT(*) FROM app_analytics.events', NULL, 'app_analytics', 450, 1, TRUE, '2025-05-20T08:00:00Z'),
    ('local-project', 'spanner', 'SELECT c.tier, COUNT(o.order_id) FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.tier', 'local-instance', 'orders_db', 120, 5, TRUE, '2025-05-20T08:05:00Z'),
    ('local-project', 'bigquery', 'SELECT event_type, COUNT(*) FROM app_analytics.events GROUP BY event_type ORDER BY count DESC', NULL, 'app_analytics', 890, 8, TRUE, '2025-05-20T08:10:00Z'),
    ('local-project', 'spanner', 'SELECT p.name, SUM(oi.total) as revenue FROM order_items oi JOIN products p ON oi.product_id = p.product_id GROUP BY p.name ORDER BY revenue DESC LIMIT 10', 'local-instance', 'orders_db', 250, 10, TRUE, '2025-05-20T08:15:00Z'),
    ('local-project', 'bigquery', 'SELECT * FROM app_analytics.orders WHERE status = ''failed''', NULL, 'app_analytics', 120, 0, TRUE, '2025-05-20T08:20:00Z'),
    ('local-project', 'memorystore', 'SELECT * FROM redis_data WHERE key LIKE ''session:*''', NULL, NULL, 35, 5, TRUE, '2025-05-20T08:25:00Z'),
    ('local-project', 'bigquery', 'SELECT DATE(created_at), event_type, COUNT(*) FROM app_analytics.events GROUP BY 1, 2', NULL, 'app_analytics', 2340, 24, FALSE, '2025-05-20T08:30:00Z'),
    ('local-project', 'bigquery', 'SELECT FORMAT_DATE(''%Y-%m-%d'', created_at) as day, event_type, COUNT(*) as cnt FROM app_analytics.events GROUP BY day, event_type', NULL, 'app_analytics', 3100, 24, TRUE, '2025-05-20T08:35:00Z');

-- UPSERT example: increment usage metric
-- INSERT INTO usage_metrics (project_id, service_id, request_count)
-- VALUES ('local-project', 'spanner', 1)
-- ON CONFLICT (project_id, service_id)
-- DO UPDATE SET request_count = usage_metrics.request_count + 1, last_updated = CURRENT_TIMESTAMP;
