package com.localcloud.emulators.cloudrun;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for Cloud Run resource path parsing.
 */
class CloudRunResourcePathTest {

    @Test
    void parseLocation_withProject() {
        String parent = "projects/test-project/locations/us-central1";
        String[] parts = parent.split("/");
        assertEquals(4, parts.length);
        assertEquals("test-project", parts[1]);
        assertEquals("us-central1", parts[3]);
    }

    @Test
    void serviceId_validFormat() {
        String serviceId = "my-service";
        assertTrue(serviceId.matches("[a-z]([a-z0-9-]{0,61}[a-z0-9])?"));
        assertFalse(serviceId.isEmpty());
    }

    @Test
    void revisionSuffix_autoGenerated() {
        String revisionId = "my-service-00001-abc";
        assertTrue(revisionId.startsWith("my-service-"));
        assertTrue(revisionId.length() > 10);
    }

    @Test
    void containerPort_validRange() {
        int port = 8080;
        assertTrue(port >= 1 && port <= 65535);
    }
}
