CREATE TABLE Transactions (
  ShardId          STRING(2)   NOT NULL,
  CustomerId       STRING(36)  NOT NULL,
  TransactionId    STRING(36)  NOT NULL,
  TransactionRef   STRING(64)  NOT NULL,
  YearMonth        STRING(6)   NOT NULL,
  RevTimestamp     TIMESTAMP   NOT NULL,
  CommitTimestamp  TIMESTAMP   NOT NULL OPTIONS (allow_commit_timestamp=true),
  Type             STRING(20)  NOT NULL,
  Direction        STRING(10)  NOT NULL,
  Status           STRING(20)  NOT NULL,
  Amount           NUMERIC     NOT NULL,
  Currency         STRING(3)   NOT NULL,
  FeeAmount        NUMERIC     NOT NULL DEFAULT (0),
  TaxAmount        NUMERIC     NOT NULL DEFAULT (0),
  NetAmount        NUMERIC     NOT NULL,
  CounterpartyType STRING(20),
  CounterpartyId   STRING(36),
  CounterpartyName STRING(200),
  SourceAccountId  STRING(36),
  DestinationAccountId STRING(36),
  Description      STRING(500),
  MerchantCategory STRING(4),
  GeoLocation      STRING(50),
  DeviceFingerprint STRING(100),
  IpAddress        STRING(45),
  RiskScore        FLOAT64,
  ComplianceFlags  ARRAY<STRING>,
  ApprovalStatus   STRING(20),
  InitiatedBy      STRING(36),
  InitiatorType    STRING(20),
  IsReversible     BOOL        NOT NULL DEFAULT (true),
  ReversedByTxId   STRING(36),
  ReversalReason   STRING(200),
  Metadata         JSON,
  SpannerCommitTS  TIMESTAMP   NOT NULL OPTIONS (allow_commit_timestamp=true),
  CONSTRAINT FK_Transactions_Customers FOREIGN KEY (ShardId, CustomerId) REFERENCES Customers (ShardId, CustomerId),
  CONSTRAINT UQ_Transactions_Ref UNIQUE (TransactionRef),
  CONSTRAINT CHK_Transactions_Type CHECK (Type IN ('PAYMENT', 'REFUND', 'TRANSFER', 'FEE', 'ADJUSTMENT', 'INTEREST')),
  CONSTRAINT CHK_Transactions_Direction CHECK (Direction IN ('DEBIT', 'CREDIT')),
  CONSTRAINT CHK_Transactions_Status CHECK (Status IN ('PENDING', 'AUTHORIZED', 'COMPLETED', 'FAILED', 'REVERSED', 'CANCELLED'))
) PRIMARY KEY (ShardId, CustomerId, YearMonth, RevTimestamp, TransactionId),
  INTERLEAVE IN PARENT Customers ON DELETE CASCADE;
